# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: MyHostedVM

steps:
- task: Maven@3
  displayName: Maven Build
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'pre-integration-test'
    options: '-P PostgreSQL'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false

- task: Docker@2
  displayName: Docker Image Build
  inputs:
    containerRegistry: 'infykubedemoregistry'
    repository: $(repository)
    tags: "1.16.0"
    command: 'build'
    Dockerfile: 'Dockerfile'
  
- task: CmdLine@2
  displayName: Trivy Scanning
  inputs:
    script: 
      trivy image --exit-code 0 --severity LOW,MEDIUM $(registryName)/$(repository):$(Build.BuildId)
      #trivy image --exit-code 0 --severity HIGH,CRITICAL $(registryName)/$(repository):$(Build.BuildId)
- task: Docker@2
  enabled: true
  displayName: Docker push
  inputs:
    containerRegistry: 'infykubedemoregistry'
    repository: '$(repository)'
    tags: "1.16.0"
    command: 'push'


- task: HelmDeploy@0
  displayName: Helm Install
  enabled: false
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'petclinick8connection'
    namespace: 'petclinic'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'spring-framework-petclinic-helm'
    releaseName: 'spring-framework-petclinic-app'
    valueFile: 'spring-framework-petclinic-helm/values.yaml'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'petclinick8connection'
    namespace: 'petclinic'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'spring-framework-petclinic-helm'
    releaseName: 'spring-framework-petclinic-app'
    valueFile: 'spring-framework-petclinic-helm/values.yaml'
- task: HelmDeploy@0
  displayName: Helm list
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'petclinick8connection'
    namespace: 'petclinic'
    command: 'ls'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'helmcharts'
    publishLocation: 'Container'

     

